forcedotcom/sfdx-core

src/org.ts
test/unit/orgTest.ts

Replaces #60 to include a test fix.
Fixes #59

fix: resolve alias before creating AuthInfo

---

examples/examples/aliasEditor/aliasEditor.ts
examples/examples/apexLogStream/apexLogStream.ts
examples/examples/apiExplorer/apiExplorer.ts
examples/examples/test/mocha.opts
examples/examples/test/unit/MockAuthInfoTest.ts
examples/examples/test/unit/MockConnectionTest.ts
examples/examples/test/unit/MockServerRequest.ts
examples/examples/test/unit/TestSandbox.ts
examples/package.json
examples/yarn.lock
src/authInfo.ts
src/config/aliases.ts
src/config/config.ts
src/config/configFile.ts
src/connection.ts
src/org.ts
src/status/streamingClient.ts
src/user.ts
test/unit/config/configFileTest.ts

also update all the incorrect docs for AsyncCreatable
Fixes: @W-5676674@, @W-5676708@

fix: use default options off the constructor

---

src/config/aliases.ts
src/config/configGroup.ts
src/config/configStore.ts
src/sfdxProject.ts
src/testSetup.ts
src/util/sfdc.ts
test/unit/config/aliasesTest.ts
test/unit/projectTest.ts
test/unit/util/sfdcTest.ts

fix: allow dot aliases and packageAliases

---

src/logger.ts
test/unit/loggerTest.ts

[W-6509405](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07B00000070ku5IAA)

fix: add debug logger that accepts a function

---

src/authInfo.ts
test/unit/authInfoTest.ts

Allow creating an AuthInfo with a parent AuthInfo to get the connected app info that was used for that auth flow. This is particularly helpful when authenticating to scratch orgs or sandbox orgs.
impl #202
This is an example:
```
const res = await this.hubOrg.getConnection().query<{
AuthCode: string,
LoginUrl: string,
SignupInstance: string
}>(`SELECT AuthCode, LoginUrl, SignupInstance FROM ScratchOrgInfo WHERE SignupUsername = '${username}'`);
const activeScratchOrg = res.records[0];
if (!activeScratchOrg) {
throw new SfdxError(`No scratch org found with username ${username} on dev hub ${parentUsername}.`, 'InvalidScratchOrName', [
`Check the scratch org exist with "sfdx force:data:soql:query -q "SELECT AuthCode FROM ScratchOrgInfo WHERE SignupUsername = '${username}'" -u …
```

feat: create authinfo with a parent authinfo

---

.circleci/config.yml
examples/yarn.lock
package.json
src/logger.ts
yarn.lock

Update the project to use @salesforce/bunyan which uses dayjs. DayJS being a lighter library compared to moment. This is the first step into making @salesforce/core compatible with bundler tools like webpack, rollup, etc.
@W-6980157@

Update to use @salesforce/bunyan

---

src/authInfo.ts
test/unit/authInfoTest.ts

Adding expiration date in Auth fields.

fix:adding expiration date in Auth Fields

---

src/util/sfdc.ts

Adds a new domain to the groupings of accepted whitelists.
@W-7543840@

Whitelistdomain Update @W-7543840@

---

messages/config.json
src/config/config.ts
src/config/configStore.ts

1. Added config key validation for ISV_Debugger_URL and ISV_Debugger_ISD
2. Added Error handling for configStore unset

Fixed config key validation and unset error handling

---

src/sfdxProject.ts
src/util/fs.ts
src/util/internal.ts
test/unit/util/fsTest.ts

adds a `resolveProjectPathSync` method, which mimics `resolveProjectPath` but synchronously

resolve project path sync

---

.circleci/config.yml
SECURITY.md
package.json

Use npm-release-management orb for releasing and testing

chore: use npm-release-management-orb

---

.circleci/config.yml

Updates config.yml to include PR validation
@W-7978550@

chore: add pr validation

---

messages/auth.json
package.json
src/authInfo.ts
src/authRemover.ts
src/exported.ts
test/unit/authInfoTest.ts
test/unit/authRemoverTest.ts
yarn.lock

- add AuthRemover class
- add listAllAuthorizations method to AuthInfo
- add setAsDefault method to AuthInfo
- add setAlias method to AuthInfo
@W-7978524@

feat: support plugin-auth

---

package.json

I've contributed the update to the definitions, DefinitelyTyped/DefinitelyTyped/pull/48101, therefore the core's dependency on this types should be updated to take advantage of the lib's functionality in both core functionality and plugin development.
On a side note, although the contribution guidelines dictate the changes should contain unit tests, current `connection` unit test, test functionality for the core's `connection` extension from `jsforce`, not the source lib behavior itself, the appropriate unit tests have been added in the source definitions repository, and the actual functionality was already part of the lib with their corresponding tests.
Fixes #307

Update jsforce type's dependency

---

src/authInfo.ts

- Adds `decrypt` option to `AuthInfo.getFields`
@W-8247994@
@W-8247935@
@W-8248004@
@W-8248034@

feat: add decrypt option to getFields

---

src/config/configAggregator.ts
src/sfdxProject.ts
test/unit/config/configAggregatorTest.ts

fix: config aggregator show updated changes from local and global config @W-8378725@

---

src/connection.ts
src/exported.ts
src/permissionSetAssignment.ts
src/user.ts
test/unit/permissionSetAssignmentTest.ts
test/unit/userTest.ts
yarn.lock

Fix a few small behaviors with the User and PermissionSetAssignment classes. I don't think they were actually being used yet

fix: updated various logic and QOL on User and PermissionSetAssignment

---

src/keyChainImpl.ts

Throw an actual error object when windows can't access a file
Work Item: 
@W-8550536@

fix(windows): throw error when file is not accessible

---

package.json

This repo is uploading wrong coverage to codecov
Run yarn test, check if the coverage is bigger than codecov.
W-5542402

Wrong coverage reported to codecov

---

CONTRIBUTING.md
DEVELOPING.md
README.md

changed CONTRIBUTING.md link to work on github or in the IDE. Minor changes to CONTRIBUTING.md and
DEVELOPING.md.

docs: changed CONTRIBUTING.md link to work on github or in the IDE

---

src/status/myDomainResolver.ts
src/util/sfdc.ts
test/unit/util/sfdcTest.ts

fix: myDomainResolver shouldn't check localhost

---

src/util/fs.ts
test/unit/util/fsTest.ts

fix: add space option to write json

---

messages/config.json
src/config/config.ts
test/unit/config/configTest.ts

fix: fixed maxQueryLimit validation

---

src/user.ts

@W-8776361@
No functional changes, just typing and jsdoc updates

fix: update password jsdoc for v51 + return type

---

src/connection.ts
src/user.ts

@W-8894798@ - client secret is being passed as an encrypted value, now passing as decrypted value

fix: pass decrypted client secret for oauth

---

src/user.ts
test/unit/userTest.ts

@W-8904350@
fixes https://github.com/forcedotcom/cli/issues/858
increases generated password length to 13
ensures that password has one of each of (uppercase, lowercase, number, and special character)

fix: meet more password requirements

---

src/webOAuthServer.ts

cherry-picking https://github.com/forcedotcom/sfdx-core/pull/380 so that we can merge this faster. 
Thanks to @hansalves for fixing this for us.
@W-8956885@
Closes #380 #383

Do not add listening event handler if oauthServer is already listening

---

src/authInfo.ts
src/status/myDomainResolver.ts
test/unit/authInfoTest.ts
test/unit/status/myDomainResolverTest.ts

@W-8956222@ Mofify jwtAudienceUrl to query cns cname for sandbox qualification

fix: qualify a sandbox url via cname lookup

---

src/authInfo.ts
test/unit/authInfoTest.ts

fix: allow = in authUrl tokens

---

package.json
src/util/sfdc.ts
test/unit/util/sfdcTest.ts
yarn.lock

fix: add another internal test env domain

---

src/config/globalInfoConfig.ts

fix: unsetAuthorization

---

README.md
src/authInfo.ts
test/unit/authInfoTest.ts

@W-8066452@ add auth:toke:set command

chore: add loginurl as option when using access token flow

---

.circleci/config.yml
messages/core.json
src/authInfo.ts
test/unit/authInfoTest.ts

This PR fixes this [GH issue](https://github.com/forcedotcom/cli/issues/1027), a breaking change to authinfo is causing only lowercase usernames.
@W-9332288@

fix: authinfo returning only lowercase usernames.

---

src/config/sfdxDataHandler.ts

Ensures that the state of the `SfdxAuthHandler` is always kept up-to-date after every change.
@W-9289452@

fix: keep track of auth changes

---

src/logger.ts

chore: fix link to logger docs

---

src/org/authInfo.ts
src/org/org.ts

fix: do not use function prop

---

src/sfdxProject.ts
test/unit/projectTest.ts

feat: @W-9517449@ Allow signupTargetLoginUrl to be overridden via env var

---

src/status/pollingClient.ts
test/unit/status/pollingClientTest.ts

fix: set retries to INFINITELY for polling client

---

MIGRATING_V2-V3.md
messages/config.md
src/config/aliases.ts
src/config/config.ts
src/config/configAggregator.ts
src/config/configFile.ts
src/config/globalInfoConfig.ts
src/exported.ts
src/global.ts
src/org/authInfo.ts
src/org/authRemover.ts
src/org/org.ts
src/org/orgConfigProperties.ts
src/sfdxError.ts
src/testSetup.ts
test/unit/config/configAggregatorTest.ts
test/unit/config/configFileTest.ts
test/unit/config/configTest.ts
test/unit/org/authInfoTest.ts
test/unit/org/authRemoverTest.ts
test/unit/org/orgTest.ts

feat: use .sf/config.json @W-9546117@

---

src/config/aliases.ts

fix: temporarily point Alias back to .sfdx

---

src/org/authRemover.ts

fix: correct jsdoc

---

src/config/globalInfoConfig.ts

fix: write sf.json contents on init

---

src/config/globalInfoConfig.ts
src/config/sfdxDataHandler.ts
test/unit/config/sfdxDataHandlerTest.ts
test/unit/org/authRemoverTest.ts
test/unit/org/orgTest.ts

fix: sfdxDataHandler tests and loading GlobalInfo

---

src/org/authRemover.ts
test/unit/org/authRemoverTest.ts

fix: use correct method to get username

---

src/config/config.ts
src/config/orgUsersConfig.ts
src/config/sandboxOrgConfig.ts
src/exported.ts
src/org/authInfo.ts
src/sfdxProject.ts
src/status/myDomainResolver.ts
src/testSetup.ts
src/util/sfdc.ts
src/util/sfdcUrl.ts
test/unit/org/authInfoTest.ts
test/unit/org/orgTest.ts
test/unit/util/sfdcTest.ts
test/unit/util/sfdcUrlTest.ts

fix: merge main(v2) into v3

---

src/messages.ts
test/unit/messagesTest.ts

fix: allows for message keys of error and errors

---

examples/examples/displayDefaults/displayDefaultUsernames.ts
messages/auth.md
messages/config.md
messages/org.md
src/config/config.ts
src/config/configAggregator.ts
src/globalInfo/globalInfoConfig.ts
src/org/authRemover.ts
src/org/org.ts
src/org/orgConfigProperties.ts
src/util/sfdcUrl.ts
test/unit/config/configAggregatorTest.ts
test/unit/config/configTest.ts
test/unit/org/authRemoverTest.ts
test/unit/org/orgTest.ts
test/unit/util/sfdcUrlTest.ts
typedocExamples/orgExamples.ts

Supports complete interoperability of sfdx and sf configs
@W-9735962@
Closes #465

feat: config interoperability

---

src/config/config.ts
test/unit/org/authRemoverTest.ts

fix: improve interoperability when unsetting

---

src/authInfo.ts
src/config/aliases.ts
src/config/authInfoConfig.ts
src/config/config.ts
src/util/fs.ts

Adds jsdoc deprecations to classes and methods that are going away in v3
@W-9789897@

chore: add deprecations

---

.circleci/config.yml
CHANGELOG.md
messages/user.md
src/config/config.ts
src/exported.ts
src/logger.ts
src/org/authInfo.ts
src/org/authRemover.ts
src/status/myDomainResolver.ts
src/util/fs.ts
src/util/getJwtAudienceUrl.ts
test/unit/loggerTest.ts
test/unit/org/authInfoTest.ts
test/unit/status/myDomainResolverTest.ts
test/unit/util/getJwtAudienceUrlTest.ts
test/unit/util/sfdcUrlTest.ts
yarn.lock

Merge main into v3

---

test/unit/org/authInfoTest.ts
yarn.lock

merge `main` into `v3`

---

src/org/authRemover.ts

Remove any tokens associated to an org username during logout
@W-9890002@

fix: remove tokens associated with org

---

messages/config.json
src/config/config.ts

See [Support Custom Templates in CLI](https://salesforce.quip.com/GA1rASFbBX30)

@W-9790306@ Custom templates config

---

messages/core.json
src/authInfo.ts
src/org.ts
test/unit/authInfoTest.ts

Improves error message to show which username (devhub username/username) is causing problems when trying to authenticate.
@W-9464074@

fix: improve error message when providing an invalid username

---

CHANGELOG.md
messages/org.json
package.json
src/org.ts
src/sfdxError.ts
src/testSetup.ts
test/unit/orgTest.ts
yarn.lock

adds logic/tests to delete a scratch org from the DevHub and removes local auth files
adds logic/tests to delete a sandbox from a production org
@W-10144418@
@W-10144443@

Deletes Scratch org + Sandboxes

---

src/authInfo.ts

https://github.com/forcedotcom/cli/issues/1298
@W-10238092@

fix: better output for authUrl errors

---

package.json
yarn.lock

bump jsforce to 1.11.0 for updated faye
@W-0@

feat: bump version of jsforce

---

src/scratchOrgSettingsGenerator.ts
test/unit/scratchOrgSettingsGeneratorTest.ts

when an invalid `project-scratch-def.json` is deployed, we now print the error messages from the server
```
➜  sfdx force:org:beta:create -f config/project-scratch-def.json -d 1 
ERROR running force:org:beta:create:  A scratch org was created with username test-pche8ahazqcb@example.com, but the settings failed to deploy
```
after
```
➜  sfdx force:org:beta:create -f config/project-scratch-def.json -d 1 
ERROR running force:org:beta:create:  A scratch org was created with username test-8curtddihgdu@example.com, but the settings failed to deploy due to 
settings/True.settings is not a valid metadata object. Check the name and casing of the file.
settings/False.settings is not a valid metadata object. Check the name and casing of the file.
```
with a `sfdx-scratch.json` like
```
"settings": …
```

fix: add error message on failed settings deploy

---

package.json

chore: reset to v3

---

package.json
src/org/org.ts
yarn.lock

fix: error literal to match the error thrown

---

src/exported.ts
src/org/authInfo.ts

feat: add handle side effect function to authinfo

---

src/testSetup.ts

fix: adjust mock org test data to conform to v3

---

src/org/authInfo.ts

Modified function to prevent a save if no changes will be made.
@W-10866138@

fix: side effects function should not save when no changes

---

.circleci/config.yml

adds plugins to CI that depend on core v3

test: add plugins that depend on core3

---

.mocharc.json
src/util/sfdcUrl.ts
test/unit/util/sfdcUrlTest.ts

[@W-10967142@](https://gus.lightning.force.com/a07EE00000uU9ygYAC)

fix: sandbox cname recognition

---

.circleci/config.yml
messages/org.json
src/org.ts
test/unit/orgTest.ts

Adds a `sandboxStatus` method to the `Org` class
WI Reference:
@W-10657353@

Org:Sandbox Status

---

src/globalInfo/sfdxDataHandler.ts

avoids async fs ops inside for loops for perf

perf: parallelize fs ops

---

package.json

chore: bump to 2.36.2

---

.circleci/config.yml
src/config/config.ts

[@W-11017499@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11017499)
See notes on V2 branch: https://github.com/forcedotcom/sfdx-core/pull/562

[V3] Fix log rotation errors

---

.circleci/config.yml
src/config/config.ts
src/config/configAggregator.ts
src/config/envVars.ts
src/exported.ts
src/org/authInfo.ts
src/org/connection.ts
src/org/scratchOrgCreate.ts
src/sfProject.ts
src/testSetup.ts
test/unit/config/configAggregatorTest.ts
test/unit/projectTest.ts

feat: add SfdxConfigAggregator

---

src/schema/validator.ts
test/unit/fixtures/schemas/invalidSchema.json
test/unit/schema/validatorTest.ts

Testing instructions in https://github.com/forcedotcom/sfdx-core/pull/577
Fixes https://github.com/forcedotcom/cli/issues/1493
[@W-11085202@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11085202)

fix: disable schemaValidation

---

package.json

bump jsforce to access new metadata rest option

feat: bump jsforce for metadata rest api

---

src/org/org.ts

fix: remove unreachable code

---

src/org/org.ts
test/unit/org/orgTest.ts

copied from from https://github.com/forcedotcom/sfdx-core/pull/546
Also improved UTs for the method and fixed some debug messages missing values.
@W-10743851@

fead: add `cloneSandbox` method

---

package.json
yarn.lock

bumping to the latest jsforce v2 release to get better autoFetchQuery support
@W-0@

fix: bump jsforce to latest v2

---

src/org/authInfo.ts
src/stateAggregator/accessors/orgAccessor.ts

fix: update AuthFields type

---

src/org/scratchOrgSettingsGenerator.ts

Need to fetch shape dir name from instance for use in packaging

fix: add getter for shape dir name

---

MIGRATING_V2-V3.md
src/stateAggregator/accessors/aliasAccessor.ts
test/unit/stateAggregator/accessors/aliasAccessorTest.ts

- Add `resolveAlias` method to `AliasAccessor`
- Update migration guide with more examples

fix: add resolveAlias

---

package.json
yarn.lock

Bumps jsforce to include support for HTTPS proxy env var.
@W-0@

fix: bump jsforce

---

package.json
src/config/config.ts
src/config/configFile.ts
src/crypto/keyChainImpl.ts
src/global.ts
src/logger.ts
test/unit/config/configFileTest.ts
yarn.lock

Description:
Remove `mkdirp` dependency in favor of native code.
Work Item
@W-11286801@

remove mkdirp in favor of native dep

---

messages/config.md
src/sfProject.ts
test/unit/projectTest.ts

Add some additional functions in SfProject for packaging needs
@W-11748608@

fix: add helper functions to project for pkging

---

src/sfProject.ts
test/unit/projectTest.ts

fix: retire use of pkgdir.name field

---

package.json
src/sfProject.ts
test/unit/projectTest.ts

fix: fix package dir functions

---

.github/workflows/notify-slack-on-pr-open.yml

Adds a github action that notifies slack when a PR is opened.

chore: add slack pr notification action

---

.github/workflows/manualRelease.yml

What does this PR do?
Switches the account used for GHA CI.
What issues does this PR fix or reference?
@W-9073995@

chore: change env var

---

messages/scratchOrgErrorCodes.md

see gh issue for details
@W-11719303@
https://github.com/forcedotcom/cli/issues/1701

fix: pass value to message correctly

---

test/unit/org/connectionTest.ts

add unit tests for recent connection perf changes
@W-12129008@

chore: add unit tests for recent connection perf changes

---

src/testSetup.ts

Adds password property to MockTestOrgData
@W-12083436@

fix: add password property to

---

src/org/scratchOrgTypes.ts

type changes for plugin-org to go to strict null checks
@W-12083557@

fix: snapshot is optional

---

src/deviceOauthService.ts

Improves error content for errors encountered during device login
@W-12484720@

fix: improve error contents for device login

---

.github/workflows/test.yml
package.json
src/org/scratchOrgCreate.ts
src/org/scratchOrgInfoApi.ts
src/org/scratchOrgSettingsGenerator.ts
yarn.lock

uses the user-supplied timeout for scratch org creation's settingsDeploy.
https://github.com/forcedotcom/cli/issues/1817
@W-12103876@

fix: correct timeout for deploy during scratch org creation

---

.mocharc.json
messages/org.md
src/org/org.ts

For non-async resume check for sandbox completion, check the status of the sandbox process before
@W-12467406@

fix: check for resumable state for sandbox resume

---

src/org/org.ts

Allow completed so auth of sandbox can be accomplished.
@W-12467406@

fix: allow completed status to be resume

---

src/logger.ts
src/org/org.ts

Moves check for a resumable sandbox above first lifecycle event.
@W-12731165@

fix: check resumable state before emitting first progress event

---

package.json
yarn.lock

bump version of jsforce to latest
@W-00000000@

fix: bump jsforce to latest beta

---

README.md

docs: add link to issues only repo

---

README.md
TEST_SETUP.md

Adds an example to stub an Sf project config

chore: add SfProjectJson stub example

---

src/sfProject.ts

types in packaging-lib had some differences here.  This captures more of what's needed.
more @W-14085765@

fix(types): additional props for packaging lib

---

src/util/fileLocking.ts

found this via one of the packaging lib NUTs' setup code.  I'm not sure that any of our production code was calling this, but there might be external code that does, or maybe we do have some.
https://github.com/forcedotcom/packaging/actions/runs/6881107933/job/18716851129
will put tests for this as a separate WI [@W-14497874@](https://gus.lightning.force.com/a07EE00001ecM0WYAU)

fix: no retries on sync lock

---

package.json
src/sfError.ts
test/unit/sfErrorTest.ts
yarn.lock

add a generic type for the SfError.data prop/get/set
I need it to fix
https://github.com/forcedotcom/source-tracking/actions/runs/6918966598/job/18821779451

feat: generic type for SfError.data

---

src/webOAuthServer.ts
test/unit/webOauthServerTest.ts

Logs and ignores requests for site icons.
@W-14755886@

fix: ignore requests for site icons

---

examples/examples/apiExplorer/apiExplorer.ts
examples/package.json
examples/yarn.lock

Updates `@salesforce/core` to v6 in the examples directory

chore: update examples

---

src/index.ts

feat: export of scratchSettingsGenerator for pkg-library

---

package.json

another export
used here https://github.com/salesforcecli/cli/blob/main/src/util/env.ts#L7

feat: export envVars top-level

---

.github/workflows/test.yml

jsforce => @jsforce/jsforce-node in xnut CI

ci: remove jsforce references in xnuts

---

package.json

chore: bump major

---

package.json
yarn.lock

ship [@W-15747484@](https://gus.lightning.force.com/a07EE00001rNcqMYAS)

fix(deps): new jsforce for loop/pword fix

---

package.json
yarn.lock

chore(dev-deps): bump ts, ts-patch

---

.github/workflows/testCoreBundling.yml

@W-0@
see if providing a default value for node version fixes the bundle test

chore: fix node version [skip validate pr]

---

src/org/scratchOrgInfoGenerator.ts
test/unit/org/scratchOrgInfoGenerator.test.ts

qa for https://github.com/forcedotcom/sfdx-core/pull/1113 with mild test reorganization
[@W-16441182@](https://gus.lightning.force.com/a07EE00001yRkIoYAK)

feat: allow $schema prop on scratch org def

---

src/util/sfdcUrl.ts
test/unit/util/sfdcUrl.test.ts

recognize workspaces orgs by their url and consider them internal

feat: workspaces support for myDomain checks

---

scripts/bundleWithCheck.js

Report the error for bundling whenever there is one found in each commit.

chore: report error whenever there is one

---

package.json
yarn.lock

Bump jsforce

---

src/org/authInfo.ts
test/unit/org/authInfo.test.ts

compatibility between authUrl and internal urls (ex: workspaces) that use a port in their instanceUrl
replacement for https://github.com/forcedotcom/sfdx-core/pull/388

feat: sfdxAuthUrl support port in instanceUrl

---

package.json
yarn.lock

See https://github.com/jsforce/jsforce/pull/1652 for more details 
[@W-17875499@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17875499)

W-17875499 bump jsforce for agent 401 loop

---

src/org/scratchOrgCreate.ts
src/org/scratchOrgErrorCodes.ts
test/unit/org/scratchOrgCreate.test.ts

update the library when scratch still in New or Creating process
@W-17889061@

fix: W-17889061 - update resume scratch 

---

package.json
yarn.lock

bump jsforce to include this fix: https://github.com/jsforce/jsforce/pull/1698
@W-18585436@

fix: bump jsforce W-18585436

---

src/config/configFile.ts
src/crypto/keyChain.ts
src/global.ts
src/logger/logger.ts
src/stateAggregator/accessors/aliasAccessor.ts
src/status/myDomainResolver.ts
src/util/fileLocking.ts
src/util/lockRetryOptions.ts
src/util/time.ts
test/unit/org/org.test.ts

minimal changes needed for web bundling support
- web detection on Global
- handling web in crypto
- injectable fs for lockfile by default
- no DNS checks from web
- pino logger uses web mode
- support for missing fs bigInt stats in memfs
refactor aliasAccessor to use the shared file locking stuff instead of having its own
@W-18471994@

@W-18471994 feat: run this library in a browser

---

src/index.ts
src/util/mutex.ts

Export `Mutex` class
@W-18653307@

feat(W-18653307): export Mutex class
