forcedotcom/sfdx-core

src/testSetup.ts
test/unit/authInfoTest.ts
test/unit/config/authInfoConfigTest.ts
test/unit/helpers.ts

This test was failing for me because I just so happened to have an auth info config on disk by the expected (to be not found) file name :P
https://github.com/forcedotcom/sfdx-core/compare/rb/authinfoconfig-test?expand=1#diff-0668b515849b2c8663f4ef5b0ca99cb8R31

test: improve AuthInfoConfig test resiliency

---

.vscode/launch.json
src/org.ts
src/testSetup.ts
test/unit/orgTest.ts

The existing `isDevHub` only checks the cached value. It won't exist for newly authed orgs so we should provide a more reliable and accurate way to determine if the org is a dev hub. Currently, the only way to do that is to check if we have access to the ScratchOrgInfo object. 
W-5797348

feat: determine if a org is a dev hub

---

src/secureBuffer.ts

aes256 is the short name for aes-256-cbc. See https://wiki.openssl.org/index.php/Enc under Cypher Algorithms.
Issue: #143

fix: Update SecureBuffer cipherName to use aes-256-cbc

---

src/authInfo.ts
test/unit/authInfoTest.ts

Use empty string for client secret when client secret is undefined

fix: use empty string in place of undefined client secret

---

src/secureBuffer.ts
test/unit/secureStringTest.ts

Changing the commit to include a test case for backward compatibility between the two aliases.

Update secureBuffer cipherName

---

DEVELOPING.md
messages/config.json
messages/core.json
package.json
src/config/configFile.ts
src/config/configStore.ts
src/logger.ts
src/schema/validator.ts
src/sfdxProject.ts
src/testSetup.ts
test/unit/config/configFileTest.ts
test/unit/config/configTest.ts
test/unit/projectTest.ts
yarn.lock

Adds some config file caching so that instances are created once per path and files are not read more than once since they are kept up to date internally.  If you really want to read the file more than once pass `force=true` to read().
Adds sfdx-project.json schema validation.  By default a warning message is displayed when validation fails, but errors can be thrown if you set the env var, `SFDX_SCHEMA_VALIDATE`
Adds a method to SfdxProjectJson to get the packageDirectories and transform any path separators in the package dir paths to match the OS.
@W-7536443@

WIP: Sh/sfdx project package dirs

---

src/logger.ts
test/unit/authInfoTest.ts
test/unit/loggerTest.ts

Fix multiple log lines when an uncaught exception happens.
There're multiple loggers printing logs when an uncaught exception happens, for example in local dev server:
```js
["sfdx", "Start", "Org", "AuthInfo", "crypto", "keyChain", "connection", "Org", "AuthInfo", "crypto", "keyChain", "connection", "TelemetryReporter", "AppInsights"]
```
The fix is to only log uncaught exception in root logger.

fix: multiple uncaught exception log fix @W-7558552@

---

package.json
src/exported.ts
src/lifecycleEvents.ts
test/unit/lifecycleEventsTest.ts
yarn.lock

In line with the efforts of __@W-5796702@__ to add command specific hooks to the Salesforce CLI, the event emitter and listener class Lifecycle has been added along with tests to this repo. This class is generic and does not have to be used only for hooks in commands. 
The tests are basic but thorough in demonstrating that every method performs as intended.

Added LifecycleEvents to Core

---

src/util/fs.ts
test/unit/util/fsTest.ts
yarn.lock

**What does this PR do?**
Brings in a few functions from toolbelt. 
- **actOn** - Recursively act on all files or directories in a directory
- **areFilesEqual** - Checks if files are the same
- **getContentHash** - Creates a hash for any string that is passed in
**Acceptance Criteria**
Unit tests should pass in both core and npm/yarn linked toolbelt using these functions. 
**Testing Notes**
yarn link from core --> toolbelt. Update actOn / areFilesEqual references to core and run tests.

Feat: adds actOn / areFilesEqual / getContentHash from toolbelt

---

messages/config.json
src/config/config.ts
src/connection.ts
test/unit/connectionTest.ts

the logic and future proofing the maxQueryLimit config value
certain queries that use `autoFetchQuery` were being limited to 10k results, now you can override queries that use that method with a config value

Wr/max query limit @W-7293174@

---

src/logger.ts
test/unit/loggerTest.ts

When log messages contain white space (excluding the ends of the string), the string should be wrapped inside `""` quotes.
For example:
`msg="this is a very long message with several white space characters in it"`

fix: wrap logfmt message with double quotes

---

src/messages.ts
test/unit/messagesTest.ts

Support array of messages, e.g.
```json
"examples": [
"sfdx config:get defaultusername",
"sfdx config:get defaultusername defaultdevhubusername instanceUrl",
"sfdx config:get defaultusername defaultdevhubusername --verbose"
]
```

feat: support array of messages when using getMessage

---

src/authInfo.ts
test/unit/authInfoTest.ts

Queries for username when username is undefined in the `buildRefreshTokenConfig`. Required to support `sfdx auth:sfdxurl:store`
@W-7978524@

fix: query for username during refresh token flow

---

src/authInfo.ts
test/unit/authInfoTest.ts

There is a new set of production sandbox instances that end in `s` rather than the traditional starting with `cs`. This code enables those sandboxes to work during auth.
@W-8115230@

fix: add new sandboxes

---

src/sfdxProject.ts
src/testSetup.ts
test/unit/projectTest.ts

Converting `salesforce-alm` to the exposure grateful-fs methods surfaced some mocking issues and other various bugs. Fix them all so we can update core usage in `salesforce-alm`.

fix: fs mocking 

---

src/config/config.ts
test/unit/config/configTest.ts

This PR adds `addAllowedProperties` static method to the `Config` class to allow the dynamic addition of `ConfigPropertyMeta` values. This supports `plugin-config` to be able load files containing the `ConfigPropertyMeta` definitions and support plugins defining their own keys (https://github.com/salesforcecli/plugin-config/pull/15)
* `addAllowedProperties` will only add `ConfigPropertyMeta` for `key` values that do not already exist in `allowedProperties`
* The default set of `allowedProperties` has been moved from the being set by the constructor and is now set on `Config` directly
* `propertyConfigMap` is changed to being a getter based on the `allowedProperties`
⚠️ Following the merging of this PR the following will need to be updated to the latest version of sfdx-core:
* …

feat: allow setting allowedProperties on config

---

package.json
yarn.lock

This PR bumps the jsforce version to take advantage of new jsforce functionality in upstream libraries.
@W-8295892@

chore: bump jsforce version

---

messages/config.json
src/sfdxProject.ts
test/unit/projectTest.ts

if a there's only one package entry in `sfdx-project.json` and it doesn't include `default: true` we will now assume that it is the default

fix: single package entry is defaulted to default package @W-8222081@

---

src/connection.ts
test/unit/connectionTest.ts

Add a function to Connection.  @W-8529337@
Several plugins use conn.query get results back and optimistically use records[0].  This reduces duplicative checks and messaging for 0 and >1 records.

feat: singleRecordQuery

---

.circleci/config.yml

@W-8667882@
Tweak to previously merged branch.  Hard to QA circle changes without actually running them.
Removes the /merge step which 
1. is no longer needed without a develop branch when we just merge into main
2. defaults to develop -> master

chore: remove circle merge step

---

src/authInfo.ts
src/util/sfdc.ts
test/unit/authInfoTest.ts

@W-8792196@ 
centralizes internal domains and exports via sfdc for all plugins to use

refactor: move isInternalUrl to sfdc

---

messages/auth.json
src/webOAuthServer.ts
test/unit/webOauthServerTest.ts

Right now, the websever oauth flow will kill the server if an auth code exchange fails, leaving a no response in the browser. This change sends the error to the browser instead.
To reproduce an auth code problem, you can deny a connected app or hack the code to introduce a character to the auth code.
@W-8789899@

fix: send oauth error to browser

---

src/connection.ts

After a bunch of real-world testing, 3 generally behaves better than 10, so it should be the default.
I'd rather that be adjustable in the ENV because it might not be right for slower connections?
This a follow-on to @W-8206747@

feat: adjustable DNS timeout

---

CHANGELOG.md
package.json
src/authInfo.ts
test/unit/authInfoTest.ts

@W-8543971@ primary: ignoring the instanceUrl flag in auth:jwt:grant and referencing non-existent properties
https://org62.lightning.force.com/lightning/r/0D50M00004IAqlISAT/view
forcedotcom/cli#217
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000006bEIUIA2/view
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008fosXIAQ/view
leaves the env as an override @amphro 
here's a file for QAing from plugin-auth.  requires a hub connected via jwt-key with some environment variables set.  https://github.com/salesforcecli/plugin-auth/blob/sm/qa-for-jwt-branches/test/commands/auth/jwt/grant.e2e.ts

fix: audiences use instanceURL

---

src/sfdxProject.ts

GUS WI: [@W-8612474@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008m6F6IAI/view)
This switches out the old `.retrieve()` method for the new `retrieveSfdxProjectJson()` method in the documentation's example.

Update sfdxProjectJson docs

---

src/config/config.ts
src/config/configAggregator.ts
test/unit/config/configAggregatorTest.ts
test/unit/config/configTest.ts

Right now, old versions of the core library will throw if there is an unknown key in the config file. If a new key is added in future versions of core, the old version doesn't know about it and will throw. THis prevents this from happening in the future.
@W-8880355@

fix: no throw on unknown config value

---

src/connection.ts
src/status/myDomainResolver.ts

This PR does the following:
- adds env var for retry frequency (`SFDX_DNS_RETRY_FREQUENCY`), which defaults to 1 second
- adds env var for disabling DNS lookup (`SFDX_DISABLE_DNS_CHECK`)
Hopefully addresses https://github.com/forcedotcom/cli/issues/820
@W-8896111@
Testing:
- edit `instanceUrl` in `~/.sfdx/<username>.json` to invalid url
- run `sfdx force:org:display -u <username>`. Command should error and show suggested actions:
```
ERROR running force:org:display:  The org cannot be found
Try this:
Verify that the org still exists
If your org is newly created, wait a minute and run your command again
If you deployed or updated the org's My Domain, logout from the CLI and authenticate again
If you are running in a CI environment with a DNS that blocks external IPs, try setting …
```

fix: revert dns polling timeout to 30 and frequency to 10

---

src/authInfo.ts
src/connection.ts
test/unit/authInfoTest.ts
test/unit/connectionTest.ts

Currently, every connection instantiation will call out and get a list of API versions. This is a waste of time considering Salesforce servers only change API versions every few months. We want to pick up quickly when the server is updated so this sets a 24 hour cache. The call is quick so this seems appropriate. 
It also introduces the environment variable `SFDX_IGNORE_API_VERSION_CACHE` to disable this cache to return to old behavior.
This also fixes an old bug auth info files where the username is an access token write to disk.
Setting `DEBUG=*connection*` you will see something like the following:
No Cache:
```
sfdx:connection DEBUG Using the latest because lastChecked=undefined and SFDX_IGNORE_API_VERSION_CACHE=false +0ms
sfdx:connection DEBUG request: …
```

feat: cache api version on auth info

---

src/connection.ts

When loading the instance API version we need to await the call to authInfo save.
@W-8927294@

fix: await the call to authInfo.save

---

src/org.ts

related to work for @W-8881661@
there's no reason to query every scratchOrgInfo (on a busy hub that someone's authenticating a new machine to, that could be a lot of data.  
The sobject either exists or doesn't so this'll be faster.

perf: small queries to identify a devHub

---

package.json
src/connection.ts
src/keyChainImpl.ts
test/unit/connectionTest.ts

@W-9014822@ 
adds the `deployRecentValidation` method to do a quick deploy with REST or SOAP
compare with https://github.com/salesforcecli/toolbelt/blob/main/src/lib/mdapi/mdApiUtil.ts#L36
and https://github.com/salesforcecli/toolbelt/blob/main/src/lib/mdapi/mdApiUtil.ts#L51

deployRecentValidation

---

src/logger.ts
test/unit/loggerTest.ts

Core's logger uses the Debug library. That library has a public field so that you can check if debug is enabled and if so, do some specific logic for debugging that could potentially degrade performance. To avoid this when debug is not enabled we need to expose this property on the Logger and have @salesforce/command library use it so that it's available for plugins.
@W-9092712@

fix: debugEnabled should be public

---

src/authInfo.ts
test/unit/authInfoTest.ts

@W-8720035@ 
will throw an error if a required field is missing when generating the URL

chore: ensure instanceUrl, clientId, refreshToken when generating URL

---

messages/core.json
src/authInfo.ts
test/unit/authInfoTest.ts

@W-8066452@
When creating an authInfo with `AuthInfo.create({ accessTokenOptions: { accessToken, instanceUrl, loginUrl: instanceUrl } });`  the new authInfo instance will contain the username/orgId.

feat: modify authInfo to return username for access token auth

---

src/authInfo.ts

exports the function `getJwtAudienceUrl` so that it can be consumed by other libraries in this WI it's going to replace `jwtAudienceUrl` from toolbelt
@W-9271200@

feat: export getJwtAudienceUrl

---

src/util/checkLightningDomain.ts
test/unit/util/checkLightningDomainTest.ts

Exports a function `checkLightningDomain` to check if an org domain is ready DNS-wise.
@W-9236226@

feat: exported function checkLightningDomain()

---

messages/user.json
src/user.ts
test/unit/userTest.ts

What does this PR do?
Changed the functionality of password:generate command. Now generating the password with the Profile Password policies and Organization Password Policies
What issues does this PR fix or reference?
@W-5829533@

feat: update generate password functionality

---

src/logger.ts
test/unit/loggerTest.ts

What does this PR do?
Modifies access token regex in logger which replaces the access token to hidden while logging the information. 
It fixes the following issue: https://github.com/forcedotcom/sfdx-core/issues/153
Testing Notes:
Try to reproduce the issue before. Test that functionality with the current branch. Test force:org:open --urlonly command with 
different tags by enabling and disabling SFDX_LOG_LEVEL
What issues does this PR fix or reference?
@W-6336711@

force:org:open force:org:open --urlonly display bug fix 

---

src/exported.ts
src/globalInfo/sfdxDataHandler.ts
src/globalInfo/types.ts
src/org/authInfo.ts
test/unit/globalInfo/accessors/orgAccessorTest.ts
test/unit/globalInfo/sfdxDataHandlerTest.ts
test/unit/org/authInfoTest.ts

Return more information from `AuthInfo.listAllAuthorizations`
@W-9670252@
@ W-9680192@

fix: return all info from AuthInfo.listAllAuthorizations

---

src/authRemover.ts

Gracefully fail when trying to unset `sf` config keys. Doing so fixes the scenario where a user has authorized with `sf` and is logging out with `sfdx`

fix: dont fail when trying to unset sf config keys

---

src/exported.ts
src/org/authInfo.ts
test/unit/org/authInfoTest.ts

@W-9670267@ Modify listAllAuthorizations function that allows caller to filter results
Default for filter is to return all authorizations to protect backward compatibility.

fix: add predicate function to list all auths

---

src/config/configAggregator.ts

By default, do not throw an error when reading a deprecated config key.

fix: optionally throw error when reading deprecated config key

---

src/crypto/crypto.ts
src/util/cache.ts
test/unit/config/configAggregatorTest.ts
test/unit/crypto/cryptoKeyFailuresTest.ts
test/unit/util/cacheTest.ts

I have been looking at perf around keychain access and found that the keychain program is invoked many times during commands like org list/env list. Each org has a new auth info constructed, which requires the keychain be accessed to fetch the crypto key used for encrypt/decrypt. I found this inefficient and this PR proposes a solution for this.
My experiments were on my local box where I have 32 orgs. When running sf env list w/o this change I see times in the ~3 second range and with this change the time is reduced to ~1.2 seconds.

fix: improve time to build auths for many orgs @W-9914839@

---

messages/config.md

@peternhale , I left the two isvXX config vars as-is.  I couldn't find any more info about them.  Can we hide them from the --help output for now?  Thx!

fix: edit the config var blurbs

---

messages/envVars.md

i made the blurbs for many of the sf vars very generic, because they work against commands that don't exist yet.  i'll have to revisit as we add more commands. 
@W-9936545@

fix: edit the env var blurbs

---

.circleci/config.yml
package.json

Force `v2.28.3` release.
This PR disables `plugin-config` failing NUTs that are blocking `release-package`. Re-enable after these are fixed in the plugin.

fix: force new release

---

.circleci/config.yml

Re-enable plugin-config NUTs, these were temporary removed in this PR: https://github.com/forcedotcom/sfdx-core/pull/492 to unblock a new sfdx-core release.

chore: re-enable plugin-config NUTs

---

package.json
src/status/streamingClient.ts
test/unit/status/streamingClientTest.ts
yarn.lock

Swaps `sfdx-faye` with `faye`.  The `faye` lib has the fix that `sfdx-faye` was applying.
@W-10288331@

feat: switch sfdx-faye with faye

---

src/connection.ts
test/unit/connectionTest.ts

avoid silly SFDX_MAX_QUERY_LIMIT warning
@W-10294697@
https://github.com/forcedotcom/cli/issues/1320

fix: no maxquery warning when records.length is 0

---

src/status/streamingClient.ts
test/unit/status/streamingClientTest.ts

since we don't want to change the public props, this just ignores them.
@W-10315739@
https://github.com/forcedotcom/cli/issues/1323

fix: faye doesn't use custom stuff passed it

---

src/user.ts

improve post-user creation auth by using instanceUrl over loginUrl (see gh issue for testing repro).
has been confirmed by customer that the fix works (see gh issue)
note about the note on the issue:
I did try deleting the org using plugin-org linked to this version of core, with no issues.
Testing notes--this only causes problem for community user create **with jwt** and **on Summer22** orgs
@W-10494033@
https://github.com/forcedotcom/cli/issues/1365

fix: prefer instanceUrl for loginUrl on user:create

---

messages/envVars.md
src/config/envVars.ts
src/logger.ts
test/unit/loggerTest.ts

Outcome of [this SPIKE](https://salesforce.quip.com/IFBwADN7GUZk#GOLABAyMYnx)
[@W-10745422@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10745422)
https://github.com/forcedotcom/cli/issues/1408
Implements the [rotating log stream](https://github.com/forcedotcom/node-bunyan#stream-type-rotating-file) supported in Bunyan into sfdx-core's logger
- Pull this branch of `sfdx-core` 
- Run `yarn build`
- Run `yarn link`
- `cd` to local `cli` (`sf`)
- Pull this branch of `sf` https://github.com/salesforcecli/cli/pull/199
- Run `yarn`
- Run `npm ls @salesforce/core`
- Confirm all `3.x` versions of core are the same
- Run `yarn link @salesforce/core`
- Run a command that will log
- Example: `SF_LOG_ROTATION_PERIOD='5000ms' SFDX_LOG_LEVEL=trace bin/dev env list`
- Note …

Rotating file logs V3

---

src/org/authInfo.ts
src/testSetup.ts
test/unit/org/authInfoTest.ts

@W-9711767@
Moves function identifyPossibleScratchOrgs (and its supporting functions) from plugin-auth to core so they can be used as part of authentication functions.

feat: move common authinfo utils to core

---

src/deviceOauthService.ts
test/unit/deviceOauthServiceTest.ts

uses `FormData` and `toBuffer` and `getHeaders` in more places. Especially `auth:device:login`
@W-10743791@

fix: more FormData with buffers and headers

---

.circleci/config.yml

removes plugins that rely on Core3 now
adds plugin-org because it relies on Core2

test: remove parking-orbit plugins from CI

---

src/org/authInfo.ts
test/unit/org/authInfoTest.ts
test/unit/org/orgTest.ts
test/unit/org/userTest.ts

Updates `AuthInfo` class to always set`isDevHub` field based on a server-check.
**Before**:
It was up to consumers to set the field based on a server-check or anything else like [passing a flag in a plugin](https://github.com/salesforcecli/plugin-auth/pull/375)
**After**:
sfdx-core will do a server-side check and set the field to either `true` or `false`.
**QA steps**:
1. Clone [plugin-auth](https://github.com/salesforcecli/plugin-auth/)
2. `yarn link @salesforce/core` into ⬆️ 
3. test all auth commands both with/without `--setdefaultdevhubusername`
4. Even without passing `--setdefaultdevhubusername `, you should see the `isDevHub` field in the authfile.
@[W-10999290](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10999290)@

feat: detect if org is a devhub at auth time

---

src/config/config.ts

[@W-11017499@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11017499)
[Slack conversation](https://salesforce-internal.slack.com/archives/G02K6C90RBJ/p1650294097684579)
Since `sfdx v7.145.0` Bunyan throws `ENOENT` errors when rotating logs. You can replicate the error with the following command:
`SFDX_LOG_ROTATION_PERIOD='1000ms' sfdx  config:list`
```
[Error: ENOENT: no such file or directory, rename '/Users/ewillhoit/.sfdx/sfdx.log.0' -> '/Users/ewillhoit/.sfdx/sfdx.log.1'] {
errno: -2,
code: 'ENOENT',
syscall: 'rename',
path: '/Users/ewillhoit/.sfdx/sfdx.log.0',
dest: '/Users/ewillhoit/.sfdx/sfdx.log.1'
}
```
This issue has been around in Bunyan for a long time ([235](https://github.com/trentm/node-bunyan/issues/235) and …

[V2] Fix log rotation errors

---

src/config/configAggregator.ts
src/config/configFile.ts
test/unit/org/orgTest.ts

Allow consumers of `ConfigAggregator` to optionally provide a list of custom config vars. This is necessary because the plugin-config init hook (which is supposed to load all custom config vars) isn't guaranteed to modify the same instance of `Config` as the one that `ConfigAggregator` will be using at run time

fix: allow ConfigAggregator to accept custom config vars

---

src/schema/validator.ts
test/unit/fixtures/schemas/invalidSchema.json
test/unit/schema/validatorTest.ts

Fixes https://github.com/forcedotcom/cli/issues/1493
Adds a few comments and tests
To validate locally reproduce the steps outlined in the above issue ^
Then add the single `validateSchema: true` line on your local _npm_ install of `sfdc-cli`
Re-run `sfdx force:data:tree:import -p data/sample-data-plan.json`
[@W-11085202@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11085202)

Disable schemaValidation [V2]

---

.circleci/config.yml

Node v14.19.2 (currently in maintenance) comes with npm v6.14.17, looks like the URL nvm-windows creates for this version stopped working:
❌  https://github.com/npm/cli/archive/v6.14.17.zip
✅  https://github.com/npm/cli/archive/v8.1.2.zip
nvm-windows:
https://github.com/coreybutler/nvm-windows/blob/5803c4f8c7766c670996fbce3fc113a9b0d95050/src/web/web.go#L65
https://github.com/coreybutler/nvm-windows/blob/5803c4f8c7766c670996fbce3fc113a9b0d95050/src/web/web.go#L27
on `main`: https://github.com/forcedotcom/sfdx-core/blob/246ee3331483efde32fbe62a04ac1a9d47ea10ab/.circleci/config.yml#L116-L120
We already run these tests on current maintenance, lts and latest on linux.
@W-0@

chore(ci): only use node LTS on Windows [ci skip]

---

src/crypto/keyChainImpl.ts
src/global.ts

NUTs that called sfdx-core to get an org/authinfo/connection weren't hitting the stubbed homedir.
@W-11120486@

fix: homedir can change after Core loads

---

src/org/connection.ts
test/unit/org/connectionTest.ts

JSForce2 changed the typing on this and it made a mess of our Connection hackery.
This removes it because jsforce2 now has this natively in query (for regular and tooling)
```
conn.tooling.autoFetchQuery<Foo>(query, { maxFetch: 50000 });
```
can just be
```
conn.tooling.query<Foo>(query, {
autoFetch: true,
});
```
[@W-11109910@](https://gus.lightning.force.com/a07EE00000wX73DYAS)

refactor: remove tooling.autoFetch

---

src/org/scratchOrgInfoApi.ts
test/unit/org/scratchOrgInfoApiTest.ts

updates the error name coming from AuthInfo:
https://github.com/forcedotcom/sfdx-core/blob/69f374cb6fd955f84258c237f67ef16c87cfda11/src/org/authInfo.ts#L753
`messages.createError` sets the error name to `NamedOrgNotFoundError`.
This is causing parking-orbited plugin-org to fail when passing a username as a vararg 
@W-10743851@

fix: update `NamedOrgNotFound` err name

---

src/org/authInfo.ts

`AuthInfo.getInstanceUrl` now checks for `org-instance-url` config key, instead of `instanceUrl`
any time you passed an auth token, instead of a username, connection requests would error with `Destination URL not reset. The URL returned from login must be set` if the config value wasn't set
fixes: https://github.com/forcedotcom/cli/issues/1564

fix: instanceUrl config now using org-instance-url

---

.github/PULL_REQUEST_TEMPLATE.md
src/util/sfdcUrl.ts
test/unit/util/sfdcUrlTest.ts

Adds support for sandboxes with enhanced domains enabled.
[Considerations for enhanced domains](https://help.salesforce.com/s/articleView?id=sf.domain_name_enhanced_considerations.htm&type=5)
> Differences Between Sandbox and Production
When you enable enhanced domains, your production My Domain login URL format, MyDomainName.my.salesforce.com, doesn’t change unless you also change your My Domain name or suffix. However, enabling enhanced domains in a sandbox adds the word “sandbox” to the org’s My Domain login URL: MyDomainName--SandboxName.sandbox.my.salesforce.com.
**QA steps**:
1. checkout the `plugin-org`parking-orbit PR locally https://github.com/salesforcecli/plugin-org/pull/332
2. checkout https://github.com/forcedotcom/sfdx-core/pull/597
3. `yarn build` and link it into …

fix(url): support sandboxes with enhanced domains enabled

---

src/testSetup.ts

Add `getConnection` to `MockTestOrgData`
```typescript
import { MockTestOrgData, testSetup } from '@salesforce/core/lib/testSetup';
const $$ = testSetup();
const testOrg = new MockTestOrgData()
await $$.stubAuths(testOrg)
const connection = await testOrg.getConnection();
```

feat: add getConnection method to MockTestOrgData

---

src/config/config.ts

Marks `maxQueryLimit` as deprecated,  right now it shows as a 'normal' config var so this method:
https://github.com/forcedotcom/sfdx-core/blob/95cfdd0269dbf84b436b26a3d5f885415e526336/src/config/configAggregator.ts#L457
returns the same key.
This should fix SfdxConfigAgg not respecting `SFDX_MAX_QUERY_LIMIT`
https://github.com/salesforcecli/plugin-data/pull/316#issuecomment-1155603365
@W-11204187@
https://github.com/forcedotcom/cli/issues/1543

fix: deprecate maxQueryLimit config var

---

src/sfProject.ts
src/testSetup.ts
test/unit/testSetupTest.ts

@W-10832700@ Utility from toolbelt/packaging had a similar function, so combining functionality from toolbelt to testSetup#uniqid

feat: modify uniqid to accept length and template

---

package.json
src/config/configStore.ts
src/config/tokensConfig.ts
src/stateAggregator/globalInfoConfig.ts
yarn.lock

Removes the `/g` flag from the `encryptedKeys` regexes so that when they are tested against the properties in an auth file they will match regardless of whether they have matched a property beforehand (as is the case when `'accessToken'` is tested before `'refreshToken'` in the same auth file)
Fixes https://github.com/forcedotcom/cli/issues/1314
@W-11349782@

fix: encrypted key regex tests will no longer be stateful

---

.circleci/config.yml
src/logger.ts

A typo is causing core to create the log file with the wrong file mode making consumers crash.

fix: set correct file mode for log file

---

src/org/authRemover.ts
src/stateAggregator/accessors/orgAccessor.ts
test/unit/stateAggregator/accessors/orgAccessorTest.ts

1. adds an option for the orgAccesor.get to ensure that the auth exists
see background here: https://salesforce.quip.com/BiusAnH1wdcE for the type problems and unexpected behavior there
2. updates AuthRemover to use the new option
3. has some tests for not-found-orgs
Note: there's something wrong in the UT for GlobalInfo tests in orgAccessorTest.ts
1. they pass when `yarn test` runs all the tests
2. 3 fail when you run just the test file.
Hypothesis: they're relying on some other test to set something and pass only because of that.
Given that GlobalInfo is going away soon, I'm not going to fix those, just making a note of it.
@W-11477147@
https://github.com/forcedotcom/cli/issues/1639

feat: orgAccessor.get has throwOnNotFound option

---

src/logger.ts

Fixes issue with `Logger` class throwing an error when trying to get the root logger.
This only happens if the logfile doesn't exists **and** the sf state folder `~/.sf` does.
The issue is in the `addLogFileStreamSync` method, when it detects there's no logfile it tries to create the sf dir but `fs.mkdirSync` fails if the dir already exists, setting `recursive: true` in the opts arg makes it idempotent.
repro:
1) `rm ~/.sf/sf.log*`
2) execute this code:
```typescript
const log = Logger.getRoot()
log.warn('lalala')
```
you should get:
`EEXIST: file already exists, mkdir '/Users/cdominguez/.sf'`
@W-11730976@

fix(logger): idempotent mkdir when creating sf dir

---

messages/envVars.md
src/config/envVars.ts
src/logger.ts

Adds support for `SF_DISABLE_LOG_FILE` and `SF_LOG_LEVEL` env vars.
The `Logger` class was checking for  `process.env.SFDX_DISABLE_LOG_FILE` only, now it supports both `SF` and `SFDX` versions.
`SF_LOG_LEVEL` was already in the `EnvironmentVariable` enum but `Logger` was checking `process.env.SFDX_LOG_LEVEL` only
**QA**:
link this change into any sf/sfdx plugin that logs something, then check:
1. both `SFDX_DISABLE_LOG_FILE` and `SF_DISABLE_LOG_FILE` set to true should disable log file writing.
2. both `SFDX_LOG_LEVEL` and `SF_LOG_LEVEL` should set the log level for the root logger, see the `logging` section of the plugin dev guide: https://github.com/salesforcecli/cli/wiki/Code-Your-Plug-In#logging 
@W-11770007@

fix(logger): support `SF_*` env vars

---

src/org/scratchOrgCreate.ts

Fix scratch org create code that deploys settings not respecting the `apiVersion` config value by correctly instantiating the `ConfigAggregator` class.
**Before**:
even having `apiVersion` set locally/globally, the code always gets undefined.
**After**:
code respects config value.
**QA**:
see gh issue linked below for debug env var val
this code is used by `sfdx force:org:create` and `sf env create scratch`/`sf env resume scratch`.
make sure the following config values/env vars are respected:
config values:
`org-api-version`
`apiVersion`
env vars:
`SFDX_API_VERSION`
`SF_ORG_API_VERSION`
https://github.com/forcedotcom/cli/issues/1719
@W-11798656@

fix(scratch): respect `apiVersion` config value

---

src/stateAggregator/accessors/tokenAccessor.ts

Updates type on `TokenAccessor.set` so that plugin-functions can compile

fix: type on TokenAccessor.set

---

messages/scratchOrgInfoApi.md
src/org/scratchOrgInfoApi.ts
test/unit/org/scratchOrgCreateTest.ts
test/unit/org/scratchOrgInfoApiTest.ts

throws a nicer error message when the `hubOrg` is not actually enabled as a `DevHub`
`ERROR running force:org:create:  The requested resource does not exist`
`ERROR running force:org:create:  Ensure that org, with id: test-podeygqvfh7u@example.com and username 00D530000008eONEAY is enabled as a DevHub`
*Messaging to be reviewed by Juliet
@W-11838125@

fix: ensure the hubOrg passes is actually a DevHub, throw error if not

---

package.json
src/sfProject.ts
test/unit/projectTest.ts

Modifies getPackageFromPath to better handle matching logic between a package dir entry's fullPath property and the path passed to the function.
@W-11903179@

fix: getPackageFromPath now handles nested package paths

---

src/logger.ts

@W-11903179@
Function addLogFileStreamSync now uses mkdir w/recursive = true

fix: function addLogFileStreamSync to use recursive mkdir

---

messages/scratchOrgErrorCodes.md

Update the url to point to the scratch org error codes documentation
[680](https://github.com/forcedotcom/sfdx-core/issues/680)

fix: incorrect url for scratch org error codes documentation

---

src/testSetup.ts

Update the restoreContext function to reset the Global.SFDX_INTEROPERABILITY value to true. 
#672

fix: reset SFDX_INTEROPERABILITY on contextRestore

---

messages/scratchOrgInfoApi.md

Updates `hubOrgIsNotDevHub` error msg.
After a user enables the dev hub settings in the org UI, `sfdx` doesn't know about this so the auth file needs to be updated (re-authenticate to the org).
See: https://github.com/forcedotcom/sfdx-core/pull/669#discussion_r1003431576
[skip ci]

fix: improve `hubOrgIsNotDevHub` error msg

---

src/schema/validator.ts
src/sfProject.ts
test/unit/projectTest.ts

**skip project.json schema validations on project read/write**
fixes noisy schema validation messages
```txt
strict mode: use allowUnionTypes to allow union type keyword at "http://schemas.salesforce.com/sfdx-project.json#/properties/replacements/items/anyOf/0/properties/replaceWhenEnv/items/properties/value" (strictTypes)
``` 
or this stuff from the logs (trying to validate non-existent global project.json)
[@W-12048460@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001CQcAWYA1/view)
---
QA notes:
link core to some plugin (plugin-source can reproduce via `source:push`) and run the command.
You should see the errors on 7.176.1 and not with core linked to your plugin.

fix: ajv allows union type schema, sfProject doesn't validate

---

src/org/connection.ts
src/org/org.ts
test/unit/org/orgTest.ts

getConnection accepts an optional version
used for apiversion flag on sfCommand-based commands
@W-12068411@

feat: getConnection accepts an optional version

---

src/testSetup.ts

Adds password to get config function in MockTestOrgData
@W-12083436@

fix: add password to mock org getConfig

---

src/messages.ts
test/unit/messagesTest.ts
test/unit/sfErrorTest.ts

messages.createError will tinker with the error key/name so that it ends in Error.  That's cool, unless you're trying to avoid breaking changes to JSON error output.
now you can avoid this pattern where you have to "fix" the name.
https://github.com/salesforcecli/plugin-trust/blob/3d6123010f0fc50203e1064ccd238b43c725c614/src/commands/plugins/trust/verify.ts#L77
@W-12173611@

feat: backward compatible messages.createError

---

LICENSE.txt
src/org/org.ts
test/unit/org/orgTest.ts

removes source tracking information from the local project when `Org.delete()` is called
@W-12375821@ https://github.com/forcedotcom/cli/issues/1879

fix: remove source tracking files with Org.delete()

---

MIGRATING_V2-V3.md

Provides greater clarity in the migration guide: fixed grammar, punctuation, spelling, and a typo.
None

docs: Fixed grammar in v2 to v3 migration guide.

---

src/logger.ts
test/unit/loggerTest.ts

On rare occasions an infinitely loop was created in our Logger class. The `console.error()` was being rethrown and caught again by the `uncaughtExceptionHandler`. A simple change to use `console.log()` prevents this loop. 
[@W-13038000@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13038000)
Fixes https://github.com/forcedotcom/cli/issues/1942
Fixes https://github.com/forcedotcom/cli/issues/1408

Fix logging loop

---

src/status/myDomainResolver.ts
test/unit/status/myDomainResolverTest.ts

adds a `SF_` equivalent env var
adds fall back to `SFDX_`
@W-13171024@

fix: use SF prefixed env vars, add UTs

---

README.md
package.json
src/exported.ts
yarn.lock

because the messageTransformer uses TS, that needs to be a regular (nonDev) dep
https://github.com/salesforcecli/plugin-deploy-retrieve/actions/runs/5257572625/jobs/9500678747?pr=659

fix: make typescript a regular dep

---

package.json
src/config/configFile.ts
src/org/authInfo.ts
src/org/scratchOrgInfoApi.ts
src/org/scratchOrgLifecycleEvents.ts
src/stateAggregator/accessors/orgAccessor.ts
src/util/jsonXmlTools.ts
src/webOAuthServer.ts
test/unit/org/authInfoTest.ts
yarn.lock

errors were swallowed by the `finally` block in ConfigFile, so that's removed.  Steve and I don't understand what that was solving, so this *might* re-expose additional errors that were being swallowed, since only ENOENT is handled.
It's probably not going to hurt reading Org files (orgAccessor is modified to only throw on JSON.parse errors and still return `null` for everything else.
also including https://github.com/forcedotcom/sfdx-core/pull/870 to get latest jsforce (NUTs seem to need this)
https://github.com/forcedotcom/cli/issues/2066
@W-13039897@

fix: tolerate broken auth files (with warning) during readAll

---

.github/workflows/perf.yml
src/org/authInfo.ts

plugin-auth `scratch-identify` NUT would fail intermittently
Tracked this down using the new logger to find it was returning multiple scratch orgs from SingleRecordQuery (!)
because soql query by string is not case sensitive and ScratchOrgInfo uses 15-char Ids.
```
sf data query -q "select Id, ExpirationDate, ScratchOrg from ScratchOrgInfo where ScratchOrg='00DDE00000485Lg'" -o na40hub 
ID                 EXPIRATIONDATE SCRATCHORG      
────────────────── ────────────── ─────────────── 
2SR4p000000fVlVGAU 2023-07-06     00DDE00000485Lg 
2SR4p000000f1MLGAY 2023-06-23     00DDE00000485lG 
Total number of records retrieved: 2.
```
This is probably only a bug on VERY active devhubs
https://github.com/salesforcecli/plugin-auth/actions/runs/5465460037/jobs/9949811105 (see 1st run of the NUTs …

fix: query scratch orgs by provided Id

---

src/logger/logger.ts
test/unit/loggerTest.ts

the env used for logger level (SF_LOG_LEVEL) was used to accepting a number.  Found this while trying `--dev-debug` and not getting the expected result with the new logger
https://github.com/salesforcecli/cli/blob/7de1e6eab96d4a2d768d6720664d9644e4842177/src/flags.ts#L31
new function handles passed-in options and env scenarios where there might be a number, and where there migt be a number that doesn't match a real level (round up to the nearest real level) to change that to a string.
Also accepts string values ex: 'debug' | 'trace' etc.
[@W-13876266@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001XVR1JYAX/view)

fix: use debug levels that are numbers from the env

---

src/org/authInfo.ts
src/testSetup.ts
test/unit/org/authInfoTest.ts
test/unit/org/userTest.ts

Save the namespace prefix of an org in its auth file.
When creating an instance of `AuthInfo`, sfdx-core will query the namespace prefix of an org and save it as `namespacePrefix`.
`Organization` object:
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_organization.htm
@W-12709731@
@W-12709714@

feat: save namespacePrefix in auth file

---

.github/workflows/perf.yml
package.json
src/util/checkLightningDomain.ts
src/util/sfdc.ts
yarn.lock

deprecate internalUrl on `sfdc` in favor of using sfdcUrl.  This removed imports of the whole network stack (myDomainResolver, etc)
also
- we use `semver` in Lifecyle, but didn't have it as an explicit dep, so now it is
- retries on `yarn install` for perf tests
https://github.com/forcedotcom/sfdx-core/actions/runs/5884778063/job/15960099482?pr=918#step:4:13

fix(perf): perf tweaks, semver is a dep

---

src/lifecycleEvents.ts
test/unit/lifecycleEventsTest.ts

new option for a unique name on lifecycle event subscribers.  If the name already exists, don't add a new listener
@W-14157566@

feat: unique listener names for lifecycle events

---

src/org/org.ts
test/unit/org/orgTest.ts

handle multiple sandbox processes in resumable state.  The error that happens has the SandboxProcesses added to err.data , and a resume lifecycle event is fired with that data for consumers to act on.
@W-13635704@

fix: handle multiple sandbox processes in resumable state

---

src/org/authInfo.ts
test/unit/org/authInfoTest.ts

We had a report of a generated clientID including base64 padding. When the customer manually modified this regex, they were able to auth correctly
https://salesforce-internal.slack.com/archives/C01LKDT1P6J/p1696536487642619?thread_ts=1696521310.500989&cid=C01LKDT1P6J
[@W-14250048@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14250048)

Allow padding on id and secret

---

src/config/config.ts
src/exported.ts

moves the sfdxConfig interop logic to the new CRDT pattern.
subsume sfdxConfig into some functions that Config can call

refactor: crdt patterns on sfdxConfig

---

src/stateAggregator/accessors/aliasAccessor.ts

makes the alias accessor handle alias files that don't have the `orgs property (we got 2 reports happening where they get a alias file with `{}` as the content, should also fix users on the old key:value alias file format).
write `{}` to your alias file (~/.sfdx/alias.json)
run `SF_ENV=development sf alias list`, see error
then if you link this branch of core into plugin-settings, with the same alias file you shouldn't get the error.
sfdx-core handles bad alias file, returns "no alias found"
```
*** Internal Diagnostic ***
TypeError: Cannot convert undefined or null to object
at Function.entries (<anonymous>)
at fileContentsRawToAliasStore (/Users/cdominguez/.nvm/versions/node/v18.17.0/lib/node_modules/@salesforce/c
li/node_modules/@salesforce/core/lib/stateAggregator/accessors/aliasAccess …
```

fix: handle alias file with no `orgs` prop

---

src/testSetup.ts

sfdx-core/testSetup makes use of `ts-sinon` for `stubMethod` but sfdx-core has `ts-sinon` in its devDeps.  So consumers who want to use testSetup have to know to add `ts-sinon` in their devDeps, and that's not intuitive at all.
error looks like
```
Error: Cannot find module '@salesforce/ts-sinon'
Require stack:
- /Users/shane.mclaughlin/eng/salesforcecli/plugin-limits/node_modules/@salesforce/core/lib/testSetup.js
- ....etc
```
Removes all the use of StubMethod.  sfdx-core will still use ts-sinon, but only in tests.

fix(deps): testSetup has non ts-sinon dependency

---

src/logger/logger.ts
test/unit/loggerTest.ts

use a memory logger when disabled
@W-14424066@
https://github.com/forcedotcom/cli/issues/2553

fix: use memory logger instance when disabled

---

src/config/configFile.ts
src/exported.ts
src/util/fileLocking.ts

makes the "lock" stuff reusable in and outside of sfdx-core without having to access it via ConfigFile
[skip-validate-pr] it's a merge into a feature branch

feat: reusable file locks outside of ConfigFile

---

.sfdevrc.json
README.md
package.json
src/messageTransformer.ts
yarn.lock

> this does NOT have to merge into the crdt patch--it could go in after that merges, or merge into that mega-PR.  It's branched from there to avoid conflicts later and to limit the scope of QA required.
ts5, plus a few breaking changes from ts in the messageTransformer
use ts-patch @W-14388558@ (STL and SDR have already been completed, this is the last step for the WI)
STL and SDR use this messageTransformer business to inline their messages.  You could link this into either one of those, run `yarn build` and then look at `messages` content to verify the transformation.
alternatively, you could take any plugin and change it (see the README update here) to do the transformation and view its messages

feat: ts5 and ts-patch

---

package.json
src/sfProject.ts
yarn.lock

use a Type for SfProject (the existing type extended ConfigContents so it's pretty open already).
modify `addPackageDirectory` to use `set` instead of relying on side-effect-mutations to the result of getContents so that the update matches the CRDT pattern.
- this was missed because, though getContents is ReadOnly, the operation was modifying mutable stuff within the object.  
@W-14085765@

fix: write safety and valid typing for sfProject

---

package.json
src/org/org.ts
src/org/scratchOrgInfoApi.ts

1. set the isScratch/isSandox/Namespace Org props during scratch org creation, along with snapshot being omitted if null.
1. only query the server for orgs with those props missing--current code was querying in the case of `false`
kinda found this doing @W-14542428@

feat: set more scratch org props at creation

---

test/unit/util/fileLockingTest.ts

ut only for the file locking functions.  The NUTs had uncovered some bugs that weren't found by UT (bugs were in the sync file locking methods).  The bugs were fixed in the previous PR and I figured this needed some tests
@W-14497874@

test: ut for fileLocking

---

src/messages.ts

simplify loading messageDirs
- you don't need to import fileURLToPath and path.dirname
```
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
Messages.importMessagesDirectory(dirname(fileURLToPath(import.meta.url)))
```
=>
```
Messages.importMessagesDirectoryFromMetaUrl(import.meta.url)
```
@W-14626332@
roll it out everywhere with https://github.com/salesforcecli/eslint-plugin-sf-plugin/pull/358

feat: import messages with 2 fewer imports

---

src/org/connection.ts

Use the updated env var for max query limit, `SF_ORG_MAX_QUERY_LIMIT`

fix: update max query limit env var

---

LICENSE.txt
src/webOAuthServer.ts

`ServerResponse.writeHead()` does not like slash characters so just remove it.
@W-14756275@

fix: remove slash char from error message

---

messages/auth.md
src/deviceOauthService.ts
test/unit/deviceOauthServiceTest.ts

Handles an HTML response from the server and throws a helpful error.  Also, if the error is just a string or doesn't have the data property set it handles it as well.
@W-14756399@

fix: handle html server response

---

src/config/configStore.ts
src/global.ts
src/org/authInfo.ts
src/schema/validator.ts
test/unit/config/configTest.ts
test/unit/globalTest.ts
test/unit/loggerTest.ts
test/unit/messagesTest.ts
test/unit/org/authInfoTest.ts

native clone in node 18+
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

refactor: use native structured-clone

---

messages/config.md
messages/envVars.md
messages/scratchOrgSettingsGenerator.md
package.json
src/config/envVars.ts
src/org/orgConfigProperties.ts
src/org/scratchOrgCreate.ts
src/org/scratchOrgSettingsGenerator.ts
test/unit/org/scratchOrgSettingsGeneratorTest.ts

Adds a new `org-capitalize-record-types` config var to allow to users to choose whether to capitalize record types defined in a scratch org definition file when creating the org.
If the config var isn't set it will still capitalize record types but will emit a warning for users to set the config var to true (we'll stop capitalization in a next major release of sfdx-core, will sync with CLI deprecation policy).
* no config var: emit warning and capitalize record types
* org-capitalize-record-types=false: no warning, don't capitalize
* org-capitalize-record-types=true: no warning, capitalize.
also, try making `org create scratch` timeout when org is ready but before it deploy settings to confirm `sf org resume scratch` also respects the config var.
1) Checkout this branch and `yarn link` it …

feat(scratch): add `org-capitalize-record-types`

---

src/config/configStore.ts
src/org/scratchOrgCreate.ts
test/unit/config/configStoreTest.ts
test/unit/config/ttlConfigTest.ts

typings are wrong for ConfigStore--`get` can return `undefined`
fixes a few things that correct typing will break, and makes notes to do this in the next major
found during, but not required for [@W-14800653@](https://gus.lightning.force.com/a07EE00001hzzuKYAQ)

refactor: configStore `get` can be undefined

---

src/config/envVars.ts

remove the CODE_COVERAGE_REQUIREMENT env/config .  Nothing is using it.
@W-14971005@

fix: remove unused env/config

---

.github/workflows/esbuild-publish.yml
scripts/build.js
scripts/tsconfig.json
scripts/updateForBundling.js

This PR creates a github workflow to make esbuild transpile the project and then publish a package @salesforce/core-bundle to npm.
It should be merged after https://github.com/forcedotcom/sfdx-core/pull/1026
[W-15022848](https://gus.lightning.force.com/a07EE00001jzD09YAE)
@W-15022848@

chore: esbuild artifacts

---

src/org/authInfo.ts
src/webOAuthServer.ts
test/unit/webOauthServerTest.ts

CLI auth should default to using code challenges and code verifiers for PKCE.  This used to be the case but somehow it was disabled.  This adds it back and also adds unit tests to ensure it stays that way.
@W-15198289@
QA:
All auth that happens as part of NUTs will verify that it doesn't break anything.  To ensure that it works with an org that has PKCE set, open your org, to to setup, search for "oauth", click on "OAuth and OpenID Connect Settings", toggle the "Require Proof Key for Code Exchange (PKCE) Extension" on.  Then do `sf org login web` targeting that org.

fix: re-enable code challenge support

---

src/sfProject.ts

Update PackageDir to include packageMetadataAccess properties that can be set in sfdx-project.json to allow a package developer to assign permission sets and permission set licenses to the build org user.
The equivalent schema change was made in PR: 
https://github.com/forcedotcom/schemas/pull/82
@W-14842023@

add properties for PS/PSL package metadata access to package dir

---

src/messages.ts
src/sfError.ts
test/tsconfig.json
test/unit/org/scratchOrgInfoApiTest.ts
test/unit/sfErrorTest.ts
tsconfig.json
typedocExamples/tsconfig.json

- bump tsconfig target/lib/etc for es2022 so we get native error.cause
- sfError extends Error instead of kit/NamedError
- adds the `name` property  
- adds the fullStack method...which now operates on stack of `error.cause` by recursing through them to build its "caused by" 
- add a new `.create` method that's less painful than the 5-prop overloaded constructor and which supports the `context` and `data` properties
- wrap method takes an `unknown` so you can wrap things in a `catch` block without having to worry about their type (previously only supported `string | Error | SfError`).  Will wrap any "other" things in an error to preserve its info in the new error's `cause`  
- the constructor (arg5) and the new `.create` also allow `cause` to be `unknown` and will narrow it to an error …

feat: improved sfError

---

src/org/scratchOrgInfoGenerator.ts

Remove 'language' from snapshot unsupported options list
@W-15482086@

feat(scratch): remove language restriction

---

src/org/scratchOrgInfoGenerator.ts
test/unit/org/scratchOrgInfoGeneratorTest.ts

Remove `namespace` from ScratchOrgInfo payload if the `nonamespace` option is true
@W-15675379@
https://github.com/forcedotcom/cli/issues/2855

fix: remove namespace if nonamespace option is set

---

.github/workflows/perf.yml
src/logger/filters.ts
src/org/authInfo.ts
test/unit/logger/filterTest.ts

Adds oauth options data to auth code exchange errors, redacting sensitive information, to improve telemetry.
@W-15758926@

fix: add oauth options data to auth code exchange errors

---

.github/workflows/bundle.yml
.github/workflows/esbuild-publish.yml
.github/workflows/testCoreBundling.yml
.github/workflows/testExternalProjects.yml
package.json
yarn.lock

- Creates new workflows `testCoreBundling.yml` and `testExternalProjects.yml` to automate testing for core bundled in apex-node and templates repo
- Extracts bundling step from `esbuild-publish.yml` into new workflow `bundle.yml`
- Automates core-bundle release for every new core github release
@W-15634761@
Test run: https://github.com/forcedotcom/sfdx-core/actions/runs/9341655590/job/25708669666?pr=1070 ✅

chore: automated tests for bundled core in apex-node and templates

---

src/lifecycleEvents.ts
test/unit/lifecycleEventsTest.ts

scenario: 
1. you build a plugin with an "early" hook (think `init` or `prerun`) which instantiates lifecycle and subscribes a listener with an uniqueId.
2. your plugin uses an older version of this library than the CLI it's installed into
3. when the "main" CLI loads Lifecycle, it tries to transfer the listeners.
4. the map of unique listeners is passed in to the new Lifecycle and deleted from the old one
5. because it was passed by ref, the delete of listeners from the old Lifecycle also deletes them from the new one
6. non-unique listeners were protected from ref-mutation bug by the spread operator (see existing code comment)
This PR adds a cloning step for the map of unique listeners and some UT to verify ref-breaking
the native `structuredClone` can't be used because the `callback` …

fix: non-reference clone of transferred listeners

---

src/org/scratchOrgCreate.ts
src/org/scratchOrgInfoApi.ts
src/org/scratchOrgSettingsGenerator.ts
test/unit/org/scratchOrgSettingsGeneratorTest.ts

- save the alias/default for the org BEFORE attempting settings deployment
- deploy error after scratch org auth is done are considered 68 (partial success)
test is here: https://github.com/salesforcecli/plugin-org/pull/1100
https://github.com/forcedotcom/cli/issues/202
@W-14879553@

fix: scratch creation partial success

---

src/config/config.ts
test/unit/config/configTest.ts

Prevent validation from being re-run on encrypted values
**Testing**
Create a plugin using `sf dev generate plugin` and add this command: 
```typescript
import { SfCommand, Flags } from '@salesforce/sf-plugins-core';
import { Config } from '@salesforce/core';
// eslint-disable-next-line sf-plugin/command-example
export default class StoreToken extends SfCommand<void> {
// eslint-disable-next-line sf-plugin/no-hardcoded-messages-commands
public static readonly summary = 'Programmatically set a token in the global config';
public static readonly flags = {
token: Flags.string({
required: true,
// eslint-disable-next-line sf-plugin/no-hardcoded-messages-flags
summary: 'a token to store',
}),
};
public async run(): Promise<void> {
const { flags } = await this.parse(StoreToken);
const config = …
```

fix: prevent validations on encrypted values

---

src/sfProject.ts
test/unit/projectTest.ts

well, this started with 
> Review JSDoc for class SfProject and SfProjectJson to ensure they are inline with code. Also review examples for correctness.
But then writing correct examples led me to notice how bad of an experience that would be.
So here's 2 new methods to make it simpler (types, etc)
And the jsdoc now reflects their existence.
@W-11338906@

feat: methods for read/write sfProjectJson.plugins

---

src/lifecycleEvents.ts

handles a cross-major-version-of-core listener without a property
https://github.com/forcedotcom/cli/issues/2935
@W-16160024@

fix: allow for undefined uniqueListerners

---

src/messages.ts
test/unit/messagesTest.ts

> [!NOTE]
> We decided to postpone this change to collect information via telemetry. Once all missing specifiers have been corrected, we will enforce them. Follow up work will be completed in [@W-16197665@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16197665)
> [!CAUTION]
> This is technically a breaking change. If we have a message somewhere that is missing a specifier, the tokens will no longer be rendered. This is a difficult thing to validate across our codebase. We could do a few things:
> - Wait until the next major release of `sfdx-core`
> - Add telemetry for when a specifier is missing and monitor it over the coming weeks
> - Only skip formatting if `messages` has a length greater than `1`
This is a solution to prevent tokens from being rendered in a …

util.format list issue

---

src/org/scratchOrgFeatureDeprecation.ts

This deprecates the CMTRecordManagedDeletion scratch org feature, which allowed deletion of managed released custom metadata records. Deletion of managed released custom metadata records is now available to all ISVs with the general ability to delete released components of managed packages.
@W-14945321@
https://github.com/forcedotcom/cli/issues/2957

@W-14945321@ Deprecate CMTRecordManagedDeletion scratch org feature

---

src/util/sfdcUrl.ts
test/unit/util/getJwtAudienceUrlTest.ts
test/unit/util/sfdcUrlTest.ts

Changes `SfdcUrl.getJwtAudienceUrl()` to use and prefer the `SF_AUDIENCE_URL` over `SFDX_AUDIENCE_URL`.  Same for the `SF_DOMAIN_RETRY` and `SFDX_DOMAIN_RETRY` env vars.
@W-16277316@

fix: use EnvVar class for audience url and domain retry env vars

---

src/sfError.ts
test/unit/sfErrorTest.ts

spreading an error, like https://github.com/salesforcecli/plugin-deploy-retrieve/blob/af41a48180f944e01f1c5e0b8ad79148b89c90c2/src/commands/project/deploy/quick.ts#L132 will pass a param that is not an instance of SfError which cause SfError.wrap to wrap it in another error.  The human output doesn't show the wrapped error, which makes it harder for users to know what's wrong.
https://github.com/forcedotcom/cli/issues/2962
@W-16297490@

fix: wrap-error-like-objects

---

.github/workflows/testCoreBundling.yml
.github/workflows/testExternalProjects.yml

This PR removes templates from the test for core-bundle 
@W-16301500@

chore: remove templates

---

src/sfProject.ts
src/testSetup.ts

clearInstance on SfProject
why no tests?
- I can't use UT with testSetup because there isn't a real project.
- I don't want to pull in testkit and do a NUT to avoid a circular dependency
needed for @W-16486531@

feat: refresh a project

---

.github/workflows/esbuild-publish.yml

@W-0000@
see if providing a default value for node version fixes the bundle publishing workflow

chore: set the default node version in bundle publishing flow [skip validate pr]

---

.github/workflows/esbuild-publish.yml
.github/workflows/onRelease.yml

- Adds a check to skip publish job if it's a beta release
@W-16304265@

chore: modify workflows to skip publish upon a prerelease

---

messages/core.md
src/org/authInfo.ts

The error message in sfdx-core needs to be updated so that the "force://" protocol language is clearer.
Also updated the `buildRefreshTokenConfig()` method to properly wrap and throw the original error.
@W-16726261@

fix: update error message for sfdx auth url

---

messages/encryption.md

We will be changing how `util.format` works when formatting messages. 
Specifiers (eg `%s`) will be required for the data to be rendered. As is, it appends data if no matching specifier is found.
More info here: https://github.com/forcedotcom/sfdx-core/pull/1099
[@W-16197665@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16197665)

Add message specifier

---

src/messages.ts
test/unit/messages.test.ts

Specifiers (eg %s) will be required for the data to be rendered. As is, it appends data if no matching specifier is found.
Much more information can be found here: https://github.com/forcedotcom/sfdx-core/pull/1099
That PR also includes the testing instructions.
[@W-16197665@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16197665)

Enforce specifiers in messages 

---

src/config/ttlConfig.ts
src/org/authInfo.ts
src/org/scratchOrgCache.ts
src/org/scratchOrgCreate.ts
src/org/scratchOrgInfoApi.ts
test/unit/config/ttlConfig.test.ts
test/unit/org/scratchOrgCreate.test.ts
test/unit/org/scratchOrgInfoApi.test.ts

1. The `signupTargetLoginUrl` override used in sfdx-project.json files was not used for scratchOrgResumes, causing auth code exchange issues during resume.  It is now used.
2. encrypts the client secret written to the scratch-create-cache.json file.
3. If the auth code exchange fails when using a loginUrl that differs from `ScratchOrgInfo.LoginUrl` another attempt is made using `ScratchOrgInfo.LoginUrl`.
4. Improves debug logging for the loginUrl used during the auth code exchange
@W-16825003@
To QA:
- use a devhub with another connected app that has a consumer secret and use it to create scratch orgs.  Ensure the clientSecret value written to the cache file is encrypted.
- resume a scratch org create where the `signupTargetLoginUrl` is necessary and ensure that login URL override is used …

fix: improved scratch org create authentication

---

.github/dependabot.yml
package.json
yarn.lock

downgrades npm-dts to support node v18

chore: downgrade npm-dts to 1.3.12

---

src/status/myDomainResolver.ts
src/util/sfdcUrl.ts
test/unit/status/myDomainResolver.test.ts
test/unit/util/sfdcUrl.test.ts

this works fine in "normal" user land with normal instanceUrls
for weird internal, the DNS lookup fails because of the port being in the url
https://nodejs.org/api/url.html#urlhostname
hostname has no port (and dns.lookup is fine)
host has the port (and dns.lookup fails)
also, workspaces url have changed (was previously `wc.dev.crm` but lately seing more `wb.dev.crm` 🤷🏻 
[@W-17167313@](https://gus.lightning.force.com/a07EE00002563cnYAA)
and also the issue where internals have to add `SF_DISABLE_DNS_CHECK:true` to avoid the port issue.

fix: dns lookup doesn't include port

---

src/stateAggregator/accessors/aliasAccessor.ts

edge case: if the `.sfdx` dir doesn't exist, it'll be created to house the newly created `alias.json` file
@W-17972181@

W-17972181 - fix: create .sfdx if necessary for alias file

---

src/crypto/keyChain.ts
src/stateAggregator/accessors/orgAccessor.ts
test/unit/stateAggregator/accessors/orgAccessor.test.ts

for orgAccessor.read(), throw an error if it's a genericKeychain error (in addition to JsonParseError).  For all other errors, at least debug log the error so it can be discovered.
for orgAccessor.readAll(), emit an error cause with the warning message so that people have more information about why an auth file is invalid.  Also, debug log that error.
@W-17979826@

W-17979826 - fix: better error handling when reading auth files

---

package.json
yarn.lock

bump jsforce to get support for `checkDeployStatus` using REST instead of SOAP:
https://github.com/jsforce/jsforce/pull/1670
@W-18012955@

fix: bump jsforce W-18012955

---

src/logger/transformStream.ts

caches regexes to avoid creating a new one per debug line
after building, copy the .js into installed CLI location / node_moduules/ @salesforce / core / lib/logger/
much similar times when using `--dev-debug` vs not
@W-17774689@

Wr/debug delay W-17774689

---

src/status/pollingClient.ts
test/unit/status/pollingClient.test.ts

adds `retryLimit` option to `PollingClient.options` to limit the amount of polling calls 
⚠️ : if set below what frequency * timeout = call count, will stop polling at the passed `retryLimit`
@W-18203875@

fix: add retry limit option to polling client W-18203875

---

src/index.ts
src/util/generateApiName.ts
test/unit/util/generateApiName.test.ts

moves a method from `agents` to `core` to be used by more 
@W-18394863@

fix: add generateApiName method to utils W-18394863

---

src/messages.ts
test/unit/messages.test.ts

actionTokens get printed outside the error message. Fix the format so it doesn't get printed twice.
**Example:**
```
actions: [
'Get the job results by running: "sf data bulk results -o john@acme.com --job-id 12345". ben@acme.com 56789',
`View the job in the org: "sf org open -o john@acme.com --path '/lightning/setup/AsyncApiJobStatus/page?address=%2F12345'". ben@acme.com 56789`
]
```
**Expected:**
```
actions: [
'Get the job results by running: "sf data bulk results -o john@acme.com --job-id 12345".',
`View the job in the org: "sf org open -o ben@acme.com --path '/lightning/setup/AsyncApiJobStatus/page?address=%2F56789'".`
]
```
@W-17099874@

fix: actionTokens error message - W-17099874

---

src/logger/logger.ts

- Adds `SF_LOG_COLORIZE` to allow users to disable colored logs, defaults to true
- Adds `SF_LOG_STDERR` to allow users to send logs to stderr, defaults to false (meaning logs will go to stdout by default)
Having these two env vars allows us to successfully emit logs from the MCP server. Cursor and vscode seem to expect stringified JSON-RPC to be sent to stdout but not for stderr. They also don't render the ansi sequences into colors. So for simplicity's sake we're going to enable these two env vars whenever users enable logging on the MCP server
@W-18724886@

feat(W-18724886): add env vars for debug logger

---

src/config/configAggregator.ts
src/stateAggregator/stateAggregator.ts
src/util/mutex.ts

Use a mutex to ensure thread-safety when getting or delete instances of ConfigAggregator or StateAggregator
@W-18653307@

feat(W-18653307): use mutex to make ConfigAgg and StateAgg thread safe

---

messages/org.md
package.json
src/org/authInfo.ts
src/org/org.ts
yarn.lock

Adds a `getFrontdoorUrl` method to the `Org` class to generate a frontdoor URL using the bridge API:
https://help.salesforce.com/s/articleView?id=xcloud.frontdoor_singleaccess.htm&type=5
Also adds an `Org.getMetadataBuilderUrl` method that gives you frontdoor URLs to specific metadata builder UIs or object manager for custom objects.
Will be used in: https://github.com/salesforcecli/mcp/pull/89
Others:
bumped jsforce
TODO:
@W-18944112@

feat(org): add `frontdoor` methods @W-18944112@

---

src/org/scratchOrgErrorCodes.ts
test/unit/org/scratchOrgErrorCodes.test.ts

Includes the last known status of the _create scratch_ job when the poll client fails due to timeout.
https://github.com/forcedotcom/cli/issues/3322
[@W-18895089@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002GtVTGYA3/view)

fix: include status of the scratch creation in intimeout  error message W-18895089

---

package.json
test/unit/org/scratchOrgErrorCodes.test.ts
yarn.lock

Bumps jsforce-node to remove `form-data` < v4.0.4 from the dependency tree:

fix: bump jsforce
